### ISSUE TITLE
Ignoring toyboxes

### ISSUE THREAD

**Issue by DidierMalenfant** [RobertCurry0216/super-date-box#1]
Just a quick heads up that if you have the toyboxes folder in .gitignore then `toybox update` won't work correctly because it records in the boxfile what toybox is currently installed and it will think everything is installed already.

Basically the idea it that toyboxes are committed with the project's repo to keep the project whole no matter what happens to the original toybox repo.

This is deliberate to avoid issues that are caused by things like git submodules. If there is enough interest we may add an option to resolve toyboxes as submodules too.

**Comment by RobertCurry0216** [comment]
oh, didn't know that. Thanks.
